<center><h1>Homework 1</h1>
    <h3>Rebecca Hinrichs</h3>
    <h4>MATH 4301 Spring 2023</h4></center>

---

In [1]:
# Import libraries & dependencies
import math
import numpy as np
import scipy as sp
from numpy import array
from scipy.linalg import lu, solve, ldl, qr
from numpy.linalg import cholesky
from numpy.random import rand
import warnings
warnings.filterwarnings("ignore")  # suppress ill-conditioned warnings
np.set_printoptions(precision = 2)

Let $A$ be a $(4 x 3)$ randomly-generated matrix<br>
> $A = \text{np.random.randint }(5, \text{size} = (4, 3))$ 

with integer elements in the interval $[0, 5)$<br>
and let $b$ be a $(4 x 1)$ randomly-generated vector<br>
> $b = \text{np.random.randint }(3, \text{size} = (4, 1))$

with integer elements in the interval $[0, 3)$.

In [2]:
# Create the matrix A
A = np.random.randint(5, size=(4,3))  # the Matrix A (4 x 3) in range [0,5)
print('\n----->> The Random Matrix A is', A.shape, '<<-----')
print(A)
print('\n----->> The Transpose Matrix A^t is', (A.T).shape, '<<-----')
print(A.T)
b = np.random.randint(3, size=(4,1))  # the Vector b (4 x 1) in range [0,3)
print('\n----->> The Solution Vector b is', b.shape, '<<-----')
print(b)


----->> The Random Matrix A is (4, 3) <<-----
[[4 4 2]
 [3 3 1]
 [3 2 0]
 [3 1 4]]

----->> The Transpose Matrix A^t is (3, 4) <<-----
[[4 3 3 3]
 [4 3 2 1]
 [2 1 0 4]]

----->> The Solution Vector b is (4, 1) <<-----
[[2]
 [1]
 [0]
 [2]]


---
1. Find the $LU$ factorization of $A^{T}A$ and $AA^{T}$ and use each factorization to solve:
> $A^{T}Ax = A^{T}b \text{  and  } AA^{T}x = b$

In [8]:
# A^t A x = A^t b
print('Finding the LU Factorization of A^t*A.....')
print('\n<===== Let P*L*U = A^t*A =====>')
P, L, U = lu(A.T @ A)
print('\nThe Permutation Matrix P is', P.shape)
print(P)
print('\nLower Triangular Matrix L is', L.shape)
print(L)
print('\nUpper Triangular Matrix U is', U.shape)
print(U)
print('\n<----- P*L*U Factorization ----->')
print(P @ L @ U)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x so that PLU*x = A^t*b <=====')
print('\n---> 1st: Solve L*y = P^t*A^t*b to find y')
y = solve(L, P.T @ A.T @ b)
print(y)
print('\n---> 2nd: Solve U*x = y to find x')
x = solve(U, y)
print(x)
print('\n====> Finding x from solve(A^t*A, A^t*b):')
x = solve(A.T @ A, A.T @ b)
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector P L U x')
print(P @ L @ U @ x)
print('\n---> Reconstruct the Vector A^t b')
print(A.T @ b)
print(f'\n====>> RESULTS: EQUAL! <<====', \
      f'\nPLU::{(A.T).shape} x {A.shape} = {(P @ L @ U).shape}', \
      f'\n→PLUx::\t{(P @ L @ U).shape} x {x.shape} = {(P @ L @ U @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→A^tb::\t{(A.T).shape} x {b.shape} = {(A.T @ b).shape}' \
      f'\n---->and PLUx = A^tb because {(P @ L @ U).shape[0]} rows = {A.shape[1]} cols\n') # A-rows v x-cols

Finding the LU Factorization of A^t*A.....

<===== Let P*L*U = A^t*A =====>

The Permutation Matrix P is (3, 3)
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

Lower Triangular Matrix L is (3, 3)
[[ 1.    0.    0.  ]
 [ 0.53  1.    0.  ]
 [ 0.79 -0.98  1.  ]]

Upper Triangular Matrix U is (3, 3)
[[43.   34.   23.  ]
 [ 0.   -3.19  8.7 ]
 [ 0.    0.    5.32]]

<----- P*L*U Factorization ----->
[[43. 34. 23.]
 [34. 30. 15.]
 [23. 15. 21.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x so that PLU*x = A^t*b <=====

---> 1st: Solve L*y = P^t*A^t*b to find y
[[17.  ]
 [ 3.91]
 [ 3.38]]

---> 2nd: Solve U*x = y to find x
[[-0.35]
 [ 0.51]
 [ 0.64]]

====> Finding x from solve(A^t*A, A^t*b):
[[-0.35]
 [ 0.51]
 [ 0.64]]

<- - - - - - - - - - - - - - - - - - - ->

---> Reconstruct the Vector P L U x
[[17.]
 [13.]
 [13.]]

---> Reconstruct the Vector A^t b
[[17]
 [13]
 [13]]

====>> RESULTS: EQUAL! <<==== 
PLU::(3, 4) x (4, 3) = (3, 3) 
→PLUx::	(3, 3) x (3, 1) = (3, 1) 
---->and on the ot

In [9]:
# A A^t x = b
print('Finding the LU Factorization of A*A^t.....')
print('\n<===== Set P*L*U = A*A^t =====>')
P, L, U = lu(A @ A.T)
print('\nThe Permutation Matrix P is', P.shape)
print(P)
print('\nLower Triangular Matrix L is', L.shape)
print(L)
print('\nUpper Triangular Matrix U is', U.shape)
print(U)
print('\n<----- P*L*U Factorization ----->')
print(P @ L @ U)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x so that PLU*x = b <=====')
print('\n---> 1st: Solve L*y = P^t*b to find y')
y = solve(L, P.T @ b)
print(y)
print('\n---> 2nd: Solve U*x = y to find x')
x = solve(U, y)
print(x)
print('\n====> Finding x from solve(A*A^t, b):')
x = solve(A @ A.T, b)
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector P L U x')
print(P @ L @ U @ x)
print('\n---> Reprint the Vector b')
print(b)
print(f'\n====>> RESULTS: UNEQUAL <<====', \
      f'\nPLU::{A.shape} x {(A.T).shape} = {(P @ L @ U).shape}', \
      f'\n→PLUx::\t{(P @ L @ U).shape} x {x.shape} = {(P @ L @ U @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→b::\t{b.shape}', \
      f'\n---->but PLUx ≠ b because {(P @ L @ U).shape[0]} rows ≠ {(A).shape[1]} cols\n') # A-rows v x-cols

Finding the LU Factorization of A*A^t.....

<===== Set P*L*U = A*A^t =====>

The Permutation Matrix P is (4, 4)
[[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]]

Lower Triangular Matrix L is (4, 4)
[[ 1.    0.    0.    0.  ]
 [ 0.67  1.    0.    0.  ]
 [ 0.56 -0.42  1.    0.  ]
 [ 0.72 -0.17  0.18  1.  ]]

Upper Triangular Matrix U is (4, 4)
[[ 3.60e+01  2.60e+01  2.00e+01  2.40e+01]
 [ 0.00e+00 -1.33e+00 -2.33e+00  1.00e+01]
 [ 0.00e+00  0.00e+00  9.17e-01  1.83e+00]
 [ 0.00e+00  0.00e+00  0.00e+00  5.15e-15]]

<----- P*L*U Factorization ----->
[[36. 26. 20. 24.]
 [26. 19. 15. 16.]
 [20. 15. 13. 11.]
 [24. 16. 11. 26.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x so that PLU*x = b <=====

---> 1st: Solve L*y = P^t*b to find y
[[ 2.  ]
 [ 0.67]
 [-0.83]
 [-0.18]]

---> 2nd: Solve U*x = y to find x
[[ 2.65e+14]
 [-3.89e+14]
 [ 7.07e+13]
 [-3.53e+13]]

====> Finding x from solve(A*A^t, b):
[[ 2.65e+14]
 [-3.89e+14]
 [ 7.07e+13]
 [-3.53e+13]]

<- - - - - - -

---
2. Find the $LDL^{T}$ factorization of $A^{T}A$ and $AA^{T}$ and use each factorization to solve:
> $A^{T}Ax = A^{T}b \text{ and } AA^{T}x = b$

In [11]:
# A^t A x = A^t b
print('Finding the LDL^t Factorization of A^t*A.....')
print('\n<===== Set L*D*L^t = A^t*A =====>')
L, D, P = ldl(A.T @ A)
print('\nThe Lower Triangular Matrix L is', L.shape)
print(L)
print('\nThe Diagonal Matrix D is', D.shape)
print(D)
print('\nThe Lower Triangular Transpose L^t is', (L.T).shape)
print(L.T)
print('\n<----- L*D*L^t Factorization ----->')
print(L @ D @ L.T)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x so that LDL^t*x = A^t*b <=====')
print('\n---> 1st: Solve L*z = A^t*b to find z')
z = solve(L, A.T @ b)
print(z)
print('\n---> 2nd: Solve D*y = z to find y')
y = solve(D, z)
print(y)
print('\n---> 3rd: Solve L^t*x = y to find x')
x = solve(L.T, y)
print(x)
print('\n====> Finding x from solve(A^t*A, A^t*b):')
x = solve(A.T @ A, A.T @ b)
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector L D L^t x')
print(L @ D @ L.T @ x)
print('\n---> Reconstruct the Vector A^t b')
print(A.T @ b)
print(f'\n====>> RESULTS: EQUAL! <<====', \
      f'\nLDL^t::{(A.T).shape} x {A.shape} = {(L @ D @ L.T).shape}', \
      f'\n→LDL^tx::\t{(L @ D @ L.T).shape} x {x.shape} = {(L @ D @ L.T @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→A^tb::\t{(A.T).shape} x {b.shape} = {(A.T @ b).shape}', \
      f'\n---->and LDL^tx = A^tb because {(L @ D @ L.T).shape[0]} rows = {A.shape[1]} cols\n') # A-rows v x-cols

Finding the LDL^t Factorization of A^t*A.....

<===== Set L*D*L^t = A^t*A =====>

The Lower Triangular Matrix L is (3, 3)
[[ 1.    0.    0.  ]
 [ 0.79  1.    0.  ]
 [ 0.53 -1.02  1.  ]]

The Diagonal Matrix D is (3, 3)
[[43.    0.    0.  ]
 [ 0.    3.12  0.  ]
 [ 0.    0.    5.44]]

The Lower Triangular Transpose L^t is (3, 3)
[[ 1.    0.79  0.53]
 [ 0.    1.   -1.02]
 [ 0.    0.    1.  ]]

<----- L*D*L^t Factorization ----->
[[43. 34. 23.]
 [34. 30. 15.]
 [23. 15. 21.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x so that LDL^t*x = A^t*b <=====

---> 1st: Solve L*z = A^t*b to find z
[[17.  ]
 [-0.44]
 [ 3.46]]

---> 2nd: Solve D*y = z to find y
[[ 0.4 ]
 [-0.14]
 [ 0.64]]

---> 3rd: Solve L^t*x = y to find x
[[-0.35]
 [ 0.51]
 [ 0.64]]

====> Finding x from solve(A^t*A, A^t*b):
[[-0.35]
 [ 0.51]
 [ 0.64]]

<- - - - - - - - - - - - - - - - - - - ->

---> Reconstruct the Vector L D L^t x
[[17.]
 [13.]
 [13.]]

---> Reconstruct the Vector A^t b
[[17]
 [13]
 [13]]

====>

In [12]:
# A A^t x = b
print('Finding the LDL^t Factorization of A*A^t.....')
print('\n<===== Set L*D*L^t = A*A^t =====>')
L, D, P = ldl(A @ A.T)
print('\nThe Lower Triangular Matrix L is', L.shape)
print(L)
print('\nThe Diagonal Matrix D is', D.shape)
print(D)
print('\nThe Lower Triangular Transpose is', (L.T).shape)
print(L.T)
print('\n<----- L*D*L^t Factorization ----->')
print(L @ D @ L.T)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x so that LDL^t*x = b <=====')
print('\n---> 1st: Solve L*z = b to find z')
z = solve(L, b)
print(z)
print('\n---> 2nd: Solve D*y = z to find y')
y = solve(D, z)
print(y)
print('\n---> 3rd: Solve L^t*x = y to find x')
x = solve(L.T, y)
print(x)
print('\n====> Finding x from solve(A*A^t, b):')
x = solve(A @ A.T, b)
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector L D L^t x')
print(L @ D @ L.T @ x)
print('\n---> Reprint the Vector b')
print(b)
print(f'\n====>> RESULTS: UNEQUAL <<====', \
      f'\nLDL^t::{A.shape} x {(A.T).shape} = {(L @ D @ L.T).shape}', \
      f'\n→LDL^tx::\t{(L @ D @ L.T).shape} x {x.shape} = {(L @ D @ L.T @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→b::\t{b.shape}', \
      f'\n---->but LDL^tx ≠ b because {(L @ D @ L.T).shape[0]} rows ≠ {A.shape[1]} cols\n') # A-rows v x-cols

Finding the LDL^t Factorization of A*A^t.....

<===== Set L*D*L^t = A*A^t =====>

The Lower Triangular Matrix L is (4, 4)
[[ 1.    0.    0.    0.  ]
 [ 0.72 -0.13  0.18  1.  ]
 [ 0.56 -0.23  1.    0.  ]
 [ 0.67  1.    0.    0.  ]]

The Diagonal Matrix D is (4, 4)
[[3.60e+01 0.00e+00 0.00e+00 0.00e+00]
 [0.00e+00 1.00e+01 0.00e+00 0.00e+00]
 [0.00e+00 0.00e+00 1.34e+00 0.00e+00]
 [0.00e+00 0.00e+00 0.00e+00 2.84e-16]]

The Lower Triangular Transpose is (4, 4)
[[ 1.    0.72  0.56  0.67]
 [ 0.   -0.13 -0.23  1.  ]
 [ 0.    0.18  1.    0.  ]
 [ 0.    1.    0.    0.  ]]

<----- L*D*L^t Factorization ----->
[[36. 26. 20. 24.]
 [26. 19. 15. 16.]
 [20. 15. 13. 11.]
 [24. 16. 11. 26.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x so that LDL^t*x = b <=====

---> 1st: Solve L*z = b to find z
[[ 2.  ]
 [ 0.67]
 [-0.96]
 [-0.18]]

---> 2nd: Solve D*y = z to find y
[[ 5.56e-02]
 [ 6.67e-02]
 [-7.11e-01]
 [-6.40e+14]]

---> 3rd: Solve L^t*x = y to find x
[[ 4.36e+14]
 [-6.40e+14]
 

---
3. Find the $Cholesky$ factorization of $A^{T}A$ and $AA^{T}$ and use each factorization to solve:
> $A^{T}Ax = A^{T}b \text{ and } AA^{T}x = b$

In [13]:
# A^t A x = A^t b
m = A.shape[0]
print('Finding the Cholesky Factorization of A^t*A with Rank',m,'.....')
A_pos = np.random.randint(5, size=(m, m))
A_symm = np.tril(A_pos) + np.tril(A_pos, -1).T
print('\nThe Positive Definite Matrix of A is', A_symm.shape)
print(A_symm)
print('\n<===== Set L*L^t = A^t*A =====>')
L = cholesky(A_symm.T @ A_symm)
print('\nThe Lower Triangular Matrix L is', L.shape)
print(L)
print('\n<----- L*L^t Factorization ----->')
print(L @ L.T)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x so that LL^t*x = A^t*b <=====')
print('\n---> 1st: Solve L*y = A^t*b to find y')
y = solve(L, A_symm.T @ b)
print(y)
print('\n---> 2nd: Solve L^t*x = y to find x')
x = solve(L.T, y)
print(x)
print('\n====> Finding x from solve(A^t*A, A^t*b):')
x = solve(A_symm.T @ A_symm, A_symm.T @ b)
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector L L^t x')
print(L @ L.T @ x)
print('\n---> Reconstruct the Vector A^t b')
print(A_symm.T @ b)
print(f'\n====>> RESULTS: EQUAL! <<====', \
      f'\nLL^t::{(A_symm.T).shape} x {A_symm.shape} = {(L @ L.T).shape}', \
      f'\n→LL^tx::\t{(L @ L.T).shape} x {x.shape} = {(L @ L.T @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→A^tb::\t{(A_symm.T).shape} x {b.shape} = {(A_symm.T @ b).shape}', \
      f'\n---->and LL^tx = A^tb because {(L @ L.T).shape[0]} rows = {A.shape[1]} cols\n') # A-rows v x-cols

Finding the Cholesky Factorization of A^t*A with Rank 4 .....

The Positive Definite Matrix of A is (4, 4)
[[1 4 0 2]
 [4 0 0 4]
 [0 0 0 3]
 [2 4 3 2]]

<===== Set L*L^t = A^t*A =====>

The Lower Triangular Matrix L is (4, 4)
[[ 4.58  0.    0.    0.  ]
 [ 2.62  5.01  0.    0.  ]
 [ 1.31  1.71  2.09  0.  ]
 [ 4.8   0.68 -0.7   3.  ]]

<----- L*L^t Factorization ----->
[[21. 12.  6. 22.]
 [12. 32. 12. 16.]
 [ 6. 12.  9.  6.]
 [22. 16.  6. 33.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x so that LL^t*x = A^t*b <=====

---> 1st: Solve L*y = A^t*b to find y
[[ 2.18e+00]
 [ 2.05e+00]
 [-1.74e-01]
 [-8.25e-17]]

---> 2nd: Solve L^t*x = y to find x
[[ 2.50e-01]
 [ 4.37e-01]
 [-8.33e-02]
 [-2.75e-17]]

====> Finding x from solve(A^t*A, A^t*b):
[[ 2.50e-01]
 [ 4.38e-01]
 [-8.33e-02]
 [ 2.34e-17]]

<- - - - - - - - - - - - - - - - - - - ->

---> Reconstruct the Vector L L^t x
[[10.]
 [16.]
 [ 6.]
 [12.]]

---> Reconstruct the Vector A^t b
[[10]
 [16]
 [ 6]
 [12]]

====>> RESUL

In [14]:
# A A^t x = b
print('Finding the Cholesky Factorization of A*A^t with Rank',m,'.....')
print('\nThe Positive Definite Matrix of A is', A_symm.shape)
print(A_symm)
print('\n<===== Set L*L^t = A*A^t =====>')
L = cholesky(A_symm @ A_symm.T)
print('\nThe Lower Triangular Matrix L is', L.shape)
print(L)
print('\n<----- L*L^t Factorization ----->')
print(L @ L.T)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x so that LL^t*x = b <=====')
print('\n---> 1st: Solve L*y = b to find y')
y = solve(L, b)
print(y)
print('\n---> 2nd: Solve L^t*x = y to find x')
x = solve(L.T, y)
print(x)
print('\n====> Finding x from solve(A*A^t, b):')
x = solve(A_symm @ A_symm.T, b)
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector L L^t x')
print(L @ L.T @ x)
print('\n---> Reprint the Vector b')
print(b)
print(f'\n====>> RESULTS: UNEQUAL <<====', \
      f'\nLL^t::{A_symm.shape} x {(A_symm.T).shape} = {(L @ L.T).shape}', \
      f'\n→LL^tx::\t{(L @ L.T).shape} x {x.shape} = {(L @ L.T @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→b::\t{b.shape}', \
      f'\n---->but LL^tx ≠ b because {(L @ L.T).shape[0]} rows ≠ {A.shape[1]} cols\n') # A-rows v x-cols

Finding the Cholesky Factorization of A*A^t with Rank 4 .....

The Positive Definite Matrix of A is (4, 4)
[[1 4 0 2]
 [4 0 0 4]
 [0 0 0 3]
 [2 4 3 2]]

<===== Set L*L^t = A*A^t =====>

The Lower Triangular Matrix L is (4, 4)
[[ 4.58  0.    0.    0.  ]
 [ 2.62  5.01  0.    0.  ]
 [ 1.31  1.71  2.09  0.  ]
 [ 4.8   0.68 -0.7   3.  ]]

<----- L*L^t Factorization ----->
[[21. 12.  6. 22.]
 [12. 32. 12. 16.]
 [ 6. 12.  9.  6.]
 [22. 16.  6. 33.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x so that LL^t*x = b <=====

---> 1st: Solve L*y = b to find y
[[ 0.44]
 [-0.03]
 [-0.25]
 [-0.08]]

---> 2nd: Solve L^t*x = y to find x
[[ 0.14]
 [ 0.04]
 [-0.13]
 [-0.03]]

====> Finding x from solve(A*A^t, b):
[[ 0.14]
 [ 0.04]
 [-0.13]
 [-0.03]]

<- - - - - - - - - - - - - - - - - - - ->

---> Reconstruct the Vector L L^t x
[[ 2.00e+00]
 [ 1.00e+00]
 [-2.78e-16]
 [ 2.00e+00]]

---> Reprint the Vector b
[[2]
 [1]
 [0]
 [2]]

====>> RESULTS: UNEQUAL <<==== 
LL^t::(4, 4) x (4, 4) = (4, 

---
4. Find the $QR$ factorization of $A$, $A^{T}A$ and $AA^{T}$. Use these factorizations to solve:
> $Ax = b \text{, } A^{T}Ax = A^{T}b \text{, and } AA^{T}x = b$

In [15]:
# Function to Apply Gram-Schmidt Orthogonalization Process
def test_independence(a):
    def gram_schmidt(a):
        q = []
        for i in range(len(a)):
            # Orthogonalization
            q_tilde = a[i]   # isn't this supposed to stay as the first value?
            for j in range(len(q)):
                q_tilde = q_tilde - (q[j].dot(a[i]))*q[j]
            # Test for dependence
            if np.sqrt(sum(q_tilde**2)) <= 1e-10:
                print('\n----- The Vectors Are Linearly Dependent -----')
                return q  # not sure why this is giving me 3 x 3 when I have a 4 x 3
            # Normalization
            else:
                q_tilde  =  q_tilde  / np.sqrt(sum(q_tilde**2)) 
                q.append(q_tilde)
        print('----- The Given Vectors Are Linearly Independent -----') 
        return q
    # Assemble the Matrix Q using the Gram-Schmidt Process
    q = gram_schmidt(A)
    print('\n----- Extract Q as unit vectors * A -----')
    for i in range(len(q)):
        print(f'Q[{i}] = {q[i]}')
    print('\n-----------------------------------')
    try:
        print('\n----- Test for OrthoNormality -----')
        for i in range(len(q)):  # Norm == sqrt(Q.element^2)
            print(f'Norm of Q[{i}] = {(sum(q[i]**2))**0.5}')
        print('-----------------------------------')
        for i in range(len(q)-1):
            for j in range(i+1, len(q)):
                print(f'Inner product of Q[{i}] and Q[{j}] = {q[i] @ q[j]}')
        print('\n-----------------------------------')
    except:
        print('\nThe Matrix Q is not Orthonormal!')

In [16]:
# Functions to Apply Gram-Schmidt Orthogonalization Process
def DotProduct(U,V):
    n = U.shape[0]
    product = 0.0
    for i in range(n):
        product += U[i,0]*V[i,0]
    return product
def Magnitude(U):
    magnitude = math.sqrt(DotProduct(U,U))
    return magnitude
def QRFactorization(A):
    m = A.shape[0]
    n = A.shape[1]
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    for i in range(n):
        W = A[:,i:i+1]
        for j in range(i):
                W = W - DotProduct(A[:,i:i+1],Q[:,j:j+1])*Q[:,j:j+1]
        Q[:,i:i+1] = W/Magnitude(W)
    R = Q.T @ A
    return (Q,R)
def QREigenfactorization(A):
    MaxIter = 60
    p = [1, 10, 20, MaxIter]
    E = Q.T @ A
    for i in range(MaxIter):
        EV = R @ Q @ Q.T
        if i+1 in p:
            print(f'Iteration {i+1}: \n{R}')
    return E

In [17]:
Q,R = QRFactorization(A.T @ A)
print(Q)
print(np.round(R,8))

[[ 0.72 -0.09 -0.68]
 [ 0.57  0.63  0.52]
 [ 0.39 -0.77  0.51]]
[[59.45 47.55 33.34]
 [ 0.    4.42 -8.7 ]
 [-0.   -0.    2.77]]


In [18]:
# A x = b
print('Finding the QR Factorization of A.....')
# test_independence(A)
print('\n<===== Set Q*R = A =====>')
Q, R = QRFactorization(A)  # let R be the square <m x m> matrix
print('\nThe Orthogonal Matrix Q is', Q.shape)
print(Q)
print('\nThe Dot Product Matrix I = Q^t*Q is', (Q.T @ Q).shape)
print(np.round(Q.T @ Q))
print('\nThe Upper Triangular Matrix R is', R.shape)
print(np.round(R))
print('\nThe Product Q^t*A agrees as', (Q.T @ A).shape)
print(np.round(Q.T @ A))
print('\n<----- Q*R Factorization ----->')
print(np.round(Q @ R))
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x: A x = Q R x = b <=====') # (4x3)(3x1)=(4x1)
print('\n---> 1st: Q R x = b') # (4x3)(3x3)(3x1)=(4x1)
print('\n---> 2nd: Q^t Q R x = Q^t b') # (3x4)(4x3)(3x3)(3x1)=(3x4)(4x1)
print('\n---> 3rd: R x = Q^t b since Q^t Q = I (Dot Product Matrix)') # (3x3)
# print('\n---> 3rd: R^t R x = R^t Q^t b')  # if Q is square
# print('\n---> 4th: since A = Q R then A^t = (Q R)^t')
# print('\n---> 5th: if A^t = (Q R)^t then A^t = Q^t R^t')
# print('\n---> 6th: R^t Q^t b = A^t b since A^t = Q^t R^t')
# print('\n---> 7th: therefore R^t R x = A^t b')
# print('\n=====> Solve for x so that R^t*R*x = A^t*b <=====')
# x = solve(R.T @ R, A.T @ b)
print('\n=====> Solve for x so that R*x = Q^t*b <=====')
x = solve(R, Q.T @ b)
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector Q R x')
print(Q @ R @ x)
print('\n---> Reconstruct the Vector A x')
print(A @ x)
print('\n---> Recall the Vector b')
print(b)
print('\n---> Reconstruct the Residual Vector QRx-b = 0')
print((Q @ R @ x) - b)
print(f'\n====>> RESULTS: UNEQUAL <<====', \
      f'\nQR::{Q.shape} x {R.shape} = {(Q @ R).shape}', \
      f'\n→QRx::\t{(Q @ R).shape} x {x.shape} = {((Q @ R) @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→b::\t{b.shape}', \
      f'\n---->but QRx ≠ b because {(Q @ R).shape[0]} ≠ {x.shape[1]}\n') # A-rows v x-cols

Finding the QR Factorization of A.....

<===== Set Q*R = A =====>

The Orthogonal Matrix Q is (4, 3)
[[ 0.61  0.47  0.31]
 [ 0.46  0.36  0.02]
 [ 0.46 -0.21 -0.85]
 [ 0.46 -0.78  0.43]]

The Dot Product Matrix I = Q^t*Q is (3, 3)
[[ 1. -0. -0.]
 [-0.  1.  0.]
 [-0.  0.  1.]]

The Upper Triangular Matrix R is (3, 3)
[[ 7.  5.  4.]
 [-0.  2. -2.]
 [-0.  0.  2.]]

The Product Q^t*A agrees as (3, 3)
[[ 7.  5.  4.]
 [-0.  2. -2.]
 [-0.  0.  2.]]

<----- Q*R Factorization ----->
[[4. 4. 2.]
 [3. 3. 1.]
 [3. 2. 0.]
 [3. 1. 4.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x: A x = Q R x = b <=====

---> 1st: Q R x = b

---> 2nd: Q^t Q R x = Q^t b

---> 3rd: R x = Q^t b since Q^t Q = I (Dot Product Matrix)

=====> Solve for x so that R*x = Q^t*b <=====
[[-0.35]
 [ 0.51]
 [ 0.64]]

<- - - - - - - - - - - - - - - - - - - ->

---> Reconstruct the Vector Q R x
[[ 1.92]
 [ 1.12]
 [-0.02]
 [ 2.01]]

---> Reconstruct the Vector A x
[[ 1.92]
 [ 1.12]
 [-0.02]
 [ 2.01]]

---> Recall the

In [29]:
# A^t A x = A^t b
print('Finding the QR Factorization of A^t*A.....')
print('\n<===== Set Q*R = A^t*A =====>')
Q, R = QRFactorization(A.T @ A)  # let BOTH be the square <m x m> matrix
print('\nThe Orthogonal Matrix Q is', Q.shape)
print(Q)
print('\nThe Dot Product Matrix I = Q^t*Q is', (Q.T @ Q).shape)
print(np.round(Q.T @ Q))
print('\nThe Upper Triangular Matrix R is', R.shape)
print(np.round(R))
print('\nThe Product Q^t*A agrees as', (Q.T @ A.T @ A).shape)
print(np.round(Q.T @ A.T @ A))
print('\n<----- Q*R Factorization ----->')
print(np.round(Q @ R))
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x: A x = Q R x = b <=====') # (4x3)(3x1)=(4x1)
print('\n---> 1st: Q R x = b') # (4x3)(3x3)(3x1)=(4x1)
print('\n---> 2nd: Q^t Q R x = Q^t b') # (3x4)(4x3)(3x3)(3x1)=(3x4)(4x1)
print('\n---> 3rd: R x = Q^t b since Q^t Q = I (Dot Product Matrix)') # (3x3)(3x1)=(3x4)(4x1)
print('\n---> 4th: R^t R x = R^t Q^t b')  # if Q is square
print('\n---> 5th: since A = Q R then A^t = (Q R)^t')
print('\n---> 6th: if A^t = (Q R)^t then A^t = Q^t R^t')
print('\n---> 7th: R^t Q^t b = A^t b since A^t = Q^t R^t')
print('\n---> 8th: therefore R^t R x = A^t b')
print('\n=====> Solve for x so that R^t*R*x = A^t*b <=====')
x = solve(R.T @ R, A.T @ b)  # if Q is square
# print('\n=====> Solve for x so that R*x = Q^t*b <=====')
# x = solve(R, Q.T @ b) # if Q is rectangular
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector Q R x')
print(Q @ R @ x)
print('\n---> Reconstruct the Vector A^t A x')
print(A.T @ A @ x)
print('\n---> Recall the Vector A^t b')
print(A.T @ b)
print('\n---> Reconstruct the Residual Vector QRx-A^tb = 0')
print((Q @ R @ x) - (A.T @ b))
print(f'\n====>> RESULTS: UNEQUAL <<====', \
      f'\nQR::{Q.shape} x {R.shape} = {(Q @ R).shape}', \
      f'\n→QRx::\t{(Q @ R).shape} x {x.shape} = {((Q @ R) @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→A^tb::\t{(A.T @ b).shape}', \
      f'\n---->We see that QRx = A^tAx because {(Q @ R).shape[0]} rows = {A.shape[1]} cols', \
      f'\n---->but observe that QRx ≠ A^tb due to linear dependence;', \
      f'\n---->therefore, x is not a unique solution.')

Finding the QR Factorization of A^t*A.....

<===== Set Q*R = A^t*A =====>

The Orthogonal Matrix Q is (3, 3)
[[ 0.72 -0.09 -0.68]
 [ 0.57  0.63  0.52]
 [ 0.39 -0.77  0.51]]

The Dot Product Matrix I = Q^t*Q is (3, 3)
[[ 1.  0. -0.]
 [ 0.  1. -0.]
 [-0. -0.  1.]]

The Upper Triangular Matrix R is (3, 3)
[[59. 48. 33.]
 [ 0.  4. -9.]
 [-0. -0.  3.]]

The Product Q^t*A agrees as (3, 3)
[[59. 48. 33.]
 [ 0.  4. -9.]
 [-0. -0.  3.]]

<----- Q*R Factorization ----->
[[43. 34. 23.]
 [34. 30. 15.]
 [23. 15. 21.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x: A x = Q R x = b <=====

---> 1st: Q R x = b

---> 2nd: Q^t Q R x = Q^t b

---> 3rd: R x = Q^t b since Q^t Q = I (Dot Product Matrix)

---> 4th: R^t R x = R^t Q^t b

---> 5th: since A = Q R then A^t = (Q R)^t

---> 6th: if A^t = (Q R)^t then A^t = Q^t R^t

---> 7th: R^t Q^t b = A^t b since A^t = Q^t R^t

---> 8th: therefore R^t R x = A^t b

=====> Solve for x so that R^t*R*x = A^t*b <=====
[[-0.61]
 [ 0.55]
 [ 0.3 ]]

<- -

In [46]:
# A A^t x = b
print('Finding the QR Factorization of A*A^t.....')
print('\n<===== Set Q*R = A*A^t =====>')
Q, R = QRFactorization(A @ A.T)  # let BOTH be the square <m x m> matrix
print('\nThe Orthogonal Matrix Q is', Q.shape)
print(Q)
print('\nThe Dot Product Matrix I = Q^t*Q is', (Q.T @ Q).shape)
print(np.round(Q.T @ Q))
print('\nThe Upper Triangular Matrix R is', R.shape)
print(np.round(R))
print('\nThe Product Q^t*A*A^t agrees as', (Q.T @ A @ A.T).shape)
print(np.round(Q.T @ A @ A.T))
print('\n<----- Q*R Factorization ----->')
print(np.round(Q @ R))
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n=====> Solve for x: A A^t x = Q R x = b <=====') # (4x3)(3x4)(4x1)=(4x4)(4x4)(4x1)
print('\n---> 1st: Q R x = b') # (4x4)(4x4)(4x1)=(4x1)
print('\n---> 2nd: Q^t Q R x = Q^t b') # (4x4)(4x4)(4x4)(4x1)=(4x4)(4x1)
print('\n---> 3rd: R x = Q^t b since Q^t Q = I (Dot Product Matrix)') # (4x4)(4x1)=(4x4)(4x1)
print('\n=====> Solve for x so that R*x = Q^t*b <=====')
x = solve(R, Q.T @ b) # if R is square
print(x)
print('\n<- - - - - - - - - - - - - - - - - - - ->')
print('\n---> Reconstruct the Vector Q R x')
print(Q @ R @ x)
print('\n---> Reconstruct the Vector A A^t x')
print(A @ A.T @ x)
print('\n---> Recall the Matrix b')
print(b)
print('\n---> Reconstruct the Residual Vector QRx-b = 0')
print((Q @ R @ x) - b)
print(f'\n====>> RESULTS: UNEQUAL <<====', \
      f'\nQR::{Q.shape} x {R.shape} = {(Q @ R).shape}', \
      f'\n→QRx::\t{(Q @ R).shape} x {x.shape} = {(Q @ R @ x).shape}', \
      f'\n---->and on the other side::', \
      f'\n→b::\t{b.shape}', \
      f'\n---->We see that QRx ≠ AA^tx because {(Q @ R).shape[0]} rows ≠ {A.shape[1]} cols', \
      f'\n---->and observe that QRx ≠ b due to linear dependence;', \
      f'\n---->therefore, x is not a solution.')

Finding the QR Factorization of A*A^t.....

<===== Set Q*R = A*A^t =====>

The Orthogonal Matrix Q is (4, 4)
[[ 0.66  0.13 -0.48 -0.59]
 [ 0.48  0.25 -0.21 -0.22]
 [ 0.37  0.46  0.79  0.69]
 [ 0.44 -0.84  0.3   0.35]]

The Dot Product Matrix I = Q^t*Q is (4, 4)
[[ 1. -0.  0. -0.]
 [-0.  1.  0. -0.]
 [ 0.  0.  1.  1.]
 [-0. -0.  1.  1.]]

The Upper Triangular Matrix R is (4, 4)
[[ 54.  39.  30.  39.]
 [ -0.   1.   3. -10.]
 [  0.   0.   1.   1.]
 [ -5.  -4.  -2.  -1.]]

The Product Q^t*A*A^t agrees as (4, 4)
[[ 54.  39.  30.  39.]
 [ -0.   1.   3. -10.]
 [  0.   0.   1.   1.]
 [ -5.  -4.  -2.  -1.]]

<----- Q*R Factorization ----->
[[39. 28. 21. 25.]
 [27. 20. 16. 16.]
 [17. 13. 11. 10.]
 [22. 15. 10. 26.]]

<- - - - - - - - - - - - - - - - - - - ->

=====> Solve for x: A A^t x = Q R x = b <=====

---> 1st: Q R x = b

---> 2nd: Q^t Q R x = Q^t b

---> 3rd: R x = Q^t b since Q^t Q = I (Dot Product Matrix)

=====> Solve for x so that R*x = Q^t*b <=====
[[-4.14e+12]
 [ 6.07e+12]
 [-1.10e+1

--- 
--- 
<center><h2>Analysis</h2></center>
In this homework assignment, we used various decomposition methods to demonstrate that Linear Algebra is Associative but not Commutative due to the order of operations being a function of transforming the basis vectors over linearly separable columns (dimensions). For this reason, the dimensional behavior of $A^{T}\times A$ resembles $A^{-1}\times A$, which is the identity matrix. When solving $Ax = b$, we're tasked with finding which vector $x$ can take $b$ from its transformed state back to its original pre-transformed state, where $x$ describes the $(\hat{i},\hat{j},\hat{k})$ coordinate of a 3D system (for example; we can actually use any number of dimensions). However, the number of dimensions must be linearly separable, which we've proven here. We've demonstrated what happens, no matter which choice of factorization method used to decompose $A\times A^{T}$- the opposite order of operations to the permutation matrix- that successful decomposition is impossible if the number of rows exceeds the number of columns in $A$. The rank of $A$ must equal the number of dimensions in the column space of $b$ in order for a solution $x$ to exist.